# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8088
  servlet:
    context-path: /mang

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    suffix: .html
    request-context-attribute: request
    cache: false  #页面不加载缓存，修改即时生效
  devtools:
    restart:
      enabled: true #设置开启热部署
#  mail:
#    username: 2301380285@qq.com #发送者的账号和密码
#    password: ukmtqhtnhgfrdhia #这个是qq邮箱中的动态安全密码
#    host: smtp.qq.com #发送的服务器
#    #配置和服务器的一个安全连接
#    properties:
#      mail:
#        smtp:
#
#      mailsmtp:
#        ssl:
#          enable: true
#    port: 465
  mail:
    host: smtp.qq.com #发送的服务器
    username: 2301380285@qq.com #发送者的账号和密码
    password: ukmtqhtnhgfrdhia #这个是qq邮箱中的动态安全密码
    default-encoding: UTF-8
    port: 465
    auth: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true
      imap:
        ssl:
          socketFactory:
            fallback: false




#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.manage.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 自定义配置
config:
  imagePath: F://image/head/
#  imagePath: /opt/cjl/image/
